# Generated by Django 4.2.4 on 2023-08-24 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0001_initial'),
        ('accounts', '0002_spotifyuser_delete_customuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='spotifyuser',
            name='playlists',
            field=models.ManyToManyField(related_name='users', to='playlists.playlist'),
        ),
    ]
